### ISSUE TITLE
Always get first xero_tenant/older, incorrect when OAuth2 return many xero_tenants

### ISSUE THREAD

**Issue by nnhansg** [XeroAPI/xero-oauth2-omniauth-sample#1]
https://github.com/XeroAPI/xero-oauth2-omniauth-sample/blob/784d93c3353a32d04ab0f254702d27f4523b0e3b/app/controllers/sessions_controller.rb#L10

Hi @JenksyGuo ,

This line of code will be incorrect when OAuth2 return many organisations and the user select specific organisation in the list. Our app doesn't know the user have selected which organisation.

Thanks.

**Comment by jenksguo** [comment]
Hey @nnhansg, sorry for the delay in my response. 

In this case, I am selecting the first organisation of the many. One Access token can work for many tenants. It is best practice to display a dropdown in your app so user can select which org to send it to. 

For 1:1 mapping, you can use /connection endpoint's UpdatedUTCDate to learn which org was connected last and use DELETE /connection call to disconnect others. 

I hope this answers your question.
