### ISSUE TITLE
OmniAuth::AuthenticityError 

### ISSUE THREAD

**Issue by sidiraihan** [XeroAPI/xero-oauth2-omniauth-sample#2]
gem 'omniauth-xero-oauth2', '~> 0.9.4'

i have an error using latest omniauth-xero-oauth2

when i click the button with link to /auth/xero_oauth2 i was expecting it will redirect to xero 

but result i got was error OmniAuth::AuthenticityError 

i think there's correlation with the release of https://github.com/omniauth/omniauth/releases/tag/v2.0.1

**Comment by sidiraihan** [comment]
Started POST "/auth/xero_oauth2" for ::1 at 2021-01-29 17:00:52 +0700
D, [2021-01-29T17:00:52.912531 #12747] DEBUG -- omniauth: (xero_oauth2) Request phase initiated.
W, [2021-01-29T17:00:52.913472 #12747]  WARN -- omniauth: Attack prevented by OmniAuth::AuthenticityTokenProtection
E, [2021-01-29T17:00:52.913904 #12747] ERROR -- omniauth: (xero_oauth2) Authentication failure! authenticity_error: OmniAuth::AuthenticityError, Forbidden
E, [2021-01-29T17:00:52.914103 #12747] ERROR -- omniauth: (xero_oauth2) Authentication failure! Forbidden: OmniAuth::AuthenticityError, Forbidden
  
OmniAuth::AuthenticityError (Forbidden):

**Comment by jenksguo** [comment]
Hi @sidiraihan, I have fixed this in the latest update. please pull down the sample and try again. 

In index, you need to use POST instead of GET since Omniauth v1.9.1
